# Generated by Django 2.1.3 on 2018-12-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0002_poll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
