# Generated by Django 2.1.3 on 2018-12-12 23:01

from django.db import migrations, models
import mediaportalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=mediaportalapp.models.generate_filename),
        ),
    ]
